# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crate_api}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Michel"]
  s.date = %q{2011-04-23}
  s.description = %q{This gem will allow for easy interaction with the Crate API to share your files!}
  s.email = %q{brian.michel@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "crate_api.gemspec",
    "lib/crate_api.rb",
    "lib/crate_api/base.rb",
    "lib/crate_api/crate.rb",
    "lib/crate_api/crateobject.rb",
    "lib/crate_api/crates.rb",
    "lib/crate_api/item.rb",
    "lib/crate_api/items.rb",
    "test/helper.rb",
    "test/test_crate_api.rb"
  ]
  s.homepage = %q{http://github.com/brianmichel/crate_api}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Interface with the Crate API}
  s.test_files = [
    "test/helper.rb",
    "test/test_crate_api.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<httmultiparty>, [">= 0.3.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.5.1"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<httmultiparty>, [">= 0.3.0"])
      s.add_dependency(%q<json>, [">= 1.5.1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<httmultiparty>, [">= 0.3.0"])
    s.add_dependency(%q<json>, [">= 1.5.1"])
  end
end

